name: Actions
on: [push]
jobs:
  integration-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tc: [tc-1, tc-2, tc-3, tc-4, tc-5, tc-6]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Run Testcase ${{ matrix.tc }}
        run: python main.py tests/${{ matrix.tc }}.in | tee /tmp/result.out
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.tc }}--output
          path: /tmp/result.out
      - name: Check Testcase ${{ matrix.tc }}
        run: tail -1 /tmp/result.out | diff tests/${{ matrix.tc }}.out -
